Update the VS Code API and use an output window to log messages
P403n1x87/austin-vscode pull request #3
Opened 2021-08-18 00:52 UTC by tonybaloney

2021-08-18 15:59 UTC, P403n1x87 commented on src/extension.ts
> +	const output :vscode.OutputChannel = vscode.window.createOutputChannel("Austin");
Can we create this inside the `AustinController` so that we don't have to pass it in via the constructor?

2021-08-18 22:44 UTC, tonybaloney commented
Updates made

2021-08-19 11:48 UTC, P403n1x87 requested changes
Great! Just a nit otherwise LGTM.

2021-08-19 11:48 UTC, P403n1x87 commented on src/controller.ts
> +    public constructor(private stats: AustinStats, ) { }
```suggestion
    public constructor(private stats: AustinStats) { }
```

2021-08-20 12:49 UTC, P403n1x87 approved these changes

2021-08-20 12:50 UTC, merged